### ISSUE TITLE
Strange error if I add file with same syntax content as previous one

### ISSUE THREAD

**Issue by bravesomesh** [zsoltszabo/node-uglifier#25]
```
/home/yolo/yolo_rpi_server/mock/server/utils.js added to sources

undefined:1786
throw new JS_Parse_Error(message, filename, line, col, pos);
^
Error
at new JS_Parse_Error (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :1778:18)
at js_error (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :1786:11)
at croak (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2299:9)
at token_error (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2307:9)
at unexpected (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2313:9)
at block_ (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2708:28)
at function_body (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2682:21)
at function (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2636:20)
at expr_atom (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :2968:24)
at maybe_unary (eval at (/home/yolo/yolo_rpi_server/mock/server/node_modules/uglify-js-harmony/tools/node.js:22:1), :3303:19)
```

**Comment by seevee** [comment]
I'm getting this error too, but I'm presently unable to diagnose the issue. Previously had to remove a cyclic dependency.

```
processing main file: /.../api/app.js                                                                                                                                                                                                                   
/.../api/app.js added to sources                                                                                                                                                                                                                        
/.../api/config/config.js added to sources                                                                                                                                                                                                              
/.../api/routes/index.js added to sources                                                                                                                                                                                                               
/.../api/routes/users.js added to sources                                                                                                                                                                                                               
/.../api/models/user.js added to sources                                                                                                                                                                                                                
/.../api/models/company.js added to sources                                                                                                                                                                                                             
/.../api/config/database.js added to sources                                                                                                                                                                                                            
/.../api/routes/companies.js added to sources                                                                                                                                                                                                           
/.../api/routes/folders.js added to sources                                                                                                                                                                                                             
/.../api/config/log.js added to sources                                                                                                                                                                                                                 
/.../api/routes/files.js added to sources                                                                                                                                                                                                               
/.../api/import/importfile.js added to sources                                                                                                                                                                                                          
/.../api/routes/views.js added to sources                                                                                                                                                                                                               
/.../api/routes/nodes.js added to sources                                                                                                                                                                                                               
/.../api/routes/links.js added to sources                                                                                                                                                                                                               
/.../api/config/passport.js added to sources                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                          
undefined:1786                                                                                                                                                                                                                                                            
    throw new JS_Parse_Error(message, filename, line, col, pos);                                                                                                                                                                                                          
    ^                                                                                                                                                                                                                                                                     
Error                                                                                                                                                                                                                                                                     
    at new JS_Parse_Error (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:1778:18)                                                                                                                       
    at js_error (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:1786:11)                                                                                                                                 
    at croak (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2299:9)                                                                                                                                     
    at token_error (eval at <anonymous> (/.../wise/api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2307:9)                                                                                                                               
    at unexpected (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2313:9)                                                                                                                                
    at block_ (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2708:28)                                                                                                                                   
    at _function_body (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2682:21)                                                                                                                           
    at function_ (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2636:20)                                                                                                                                
    at expr_atom (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:2968:24)                                                                                                                                
    at maybe_unary (eval at <anonymous> (/.../api/node_modules/uglify-js-harmony/tools/node.js:22:1), <anonymous>:3303:19)
```

**Comment by notedit** [comment]
same error
